/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

import '@soybean-react/vite-plugin-react-router';

declare module "@soybean-react/vite-plugin-react-router" {

  /**
   * route map
   */
  export type RouteMap = {
    "not-found": "*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "document": "/document";
    "document_project": "/document/project";
    "document_project-link": "/document/project-link";
    "document_react": "/document/react";
    "document_vite": "/document/vite";
    "document_unocss": "/document/unocss";
    "document_procomponents": "/document/procomponents";
    "document_antd": "/document/antd";
    "document_ui": "/document/ui";
    "(base)_about": "/about";
    "(base)_dashboard": "/dashboard";
    "(base)_dashboard_ops": "/dashboard/ops";
    "(base)_dashboard_overview": "/dashboard/overview";
    "(base)_delivery": "/delivery";
    "(base)_delivery_master": "/delivery/master";
    "(base)_delivery_master_carriers": "/delivery/master/carriers";
    "(base)_delivery_master_drivers": "/delivery/master/drivers";
    "(base)_delivery_master_routes": "/delivery/master/routes";
    "(base)_delivery_ops": "/delivery/ops";
    "(base)_delivery_ops_exceptions": "/delivery/ops/exceptions";
    "(base)_delivery_ops_tasks": "/delivery/ops/tasks";
    "(base)_finance": "/finance";
    "(base)_finance_customer": "/finance/customer";
    "(base)_finance_customer_bills": "/finance/customer/bills";
    "(base)_finance_customer_settlements": "/finance/customer/settlements";
    "(base)_finance_supplier": "/finance/supplier";
    "(base)_finance_supplier_bills": "/finance/supplier/bills";
    "(base)_finance_supplier_settlements": "/finance/supplier/settlements";
    "(base)_master": "/master";
    "(base)_master_customer": "/master/customer";
    "(base)_master_customer_companies": "/master/customer/companies";
    "(base)_master_customer_list": "/master/customer/list";
    "(base)_master_customer_operate": "/master/customer/operate";
    "(base)_master_customer_operate_[id]": "/master/customer/operate/:id";
    "(base)_master_customer_sub-accounts": "/master/customer/sub-accounts";
    "(base)_master_customer_tags": "/master/customer/tags";
    "(base)_master_goods": "/master/goods";
    "(base)_master_goods_list": "/master/goods/list";
    "(base)_master_goods_operate": "/master/goods/operate";
    "(base)_master_goods_operate_[id]": "/master/goods/operate/:id";
    "(base)_master_goods_types": "/master/goods/types";
    "(base)_master_goods_units": "/master/goods/units";
    "(base)_master_pricing": "/master/pricing";
    "(base)_master_pricing_protocol-goods": "/master/pricing/protocol-goods";
    "(base)_master_pricing_protocols": "/master/pricing/protocols";
    "(base)_master_pricing_quotation-goods": "/master/pricing/quotation-goods";
    "(base)_master_pricing_quotations": "/master/pricing/quotations";
    "(base)_master_supply": "/master/supply";
    "(base)_master_supply_purchase-rules": "/master/supply/purchase-rules";
    "(base)_master_supply_purchasers": "/master/supply/purchasers";
    "(base)_master_supply_suppliers": "/master/supply/suppliers";
    "(base)_master_supply_wares": "/master/supply/wares";
    "(base)_orders": "/orders";
    "(base)_orders_after-sales": "/orders/after-sales";
    "(base)_orders_detail": "/orders/detail";
    "(base)_orders_detail_[id]": "/orders/detail/:id";
    "(base)_orders_edit": "/orders/edit";
    "(base)_orders_edit_[id]": "/orders/edit/:id";
    "(base)_orders_list": "/orders/list";
    "(base)_orders_pickup-tasks": "/orders/pickup-tasks";
    "(base)_purchase": "/purchase";
    "(base)_purchase_orders": "/purchase/orders";
    "(base)_purchase_plans": "/purchase/plans";
    "(base)_reports": "/reports";
    "(base)_reports_after-sales": "/reports/after-sales";
    "(base)_reports_purchase": "/reports/purchase";
    "(base)_reports_purchase_goods": "/reports/purchase/goods";
    "(base)_reports_purchase_purchasers": "/reports/purchase/purchasers";
    "(base)_reports_purchase_suppliers": "/reports/purchase/suppliers";
    "(base)_reports_sales": "/reports/sales";
    "(base)_reports_sales_areas": "/reports/sales/areas";
    "(base)_reports_sales_categories": "/reports/sales/categories";
    "(base)_reports_sales_customers": "/reports/sales/customers";
    "(base)_reports_sales_goods": "/reports/sales/goods";
    "(base)_reports_stock": "/reports/stock";
    "(base)_reports_stock_daily": "/reports/stock/daily";
    "(base)_reports_stock_daily-goods": "/reports/stock/daily-goods";
    "(base)_storage": "/storage";
    "(base)_storage_in": "/storage/in";
    "(base)_storage_in_other": "/storage/in/other";
    "(base)_storage_in_purchase": "/storage/in/purchase";
    "(base)_storage_in_sales-return": "/storage/in/sales-return";
    "(base)_storage_out": "/storage/out";
    "(base)_storage_out_other": "/storage/out/other";
    "(base)_storage_out_purchase-return": "/storage/out/purchase-return";
    "(base)_storage_out_sale": "/storage/out/sale";
    "(base)_storage_query": "/storage/query";
    "(base)_storage_query_batches": "/storage/query/batches";
    "(base)_storage_query_ledgers": "/storage/query/ledgers";
    "(base)_storage_query_overview": "/storage/query/overview";
    "(base)_storage_query_stocktaking": "/storage/query/stocktaking";
    "(base)_system": "/system";
    "(base)_system_auth": "/system/auth";
    "(base)_system_auth_departments": "/system/auth/departments";
    "(base)_system_auth_menus": "/system/auth/menus";
    "(base)_system_auth_roles": "/system/auth/roles";
    "(base)_system_auth_roles_[...slug]": "/system/auth/roles/*";
    "(base)_system_auth_users": "/system/auth/users";
    "(base)_system_auth_users_[id]": "/system/auth/users/:id";
    "(base)_system_ops": "/system/ops";
    "(base)_system_ops_notices": "/system/ops/notices";
    "(base)_system_ops_settings": "/system/ops/settings";
    "(base)_system_tools": "/system/tools";
    "(base)_system_tools_files": "/system/tools/files";
    "(base)_system_tools_import-export": "/system/tools/import-export";
    "(base)_system_tools_print-templates": "/system/tools/print-templates";
    "(base)_traceability": "/traceability";
    "(base)_traceability_inspection-reports": "/traceability/inspection-reports";
    "(base)_traceability_push-logs": "/traceability/push-logs";
    "(base)_traceability_records": "/traceability/records";
    "(base)_user-center": "/user-center";
    "(blank)_login": "/login";
    "(blank)_login_code-login": "/login/code-login";
    "(blank)_login_register": "/login/register";
    "(blank)_login_reset-pwd": "/login/reset-pwd";
    "(blank)_login-out": "/login-out";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "iframe-page": "/iframe-page";
    "root": "/";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document"
    | "document_project"
    | "document_project-link"
    | "document_react"
    | "document_vite"
    | "document_unocss"
    | "document_procomponents"
    | "document_antd"
    | "document_ui"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "(base)"
    | "(blank)"
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "root"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "not-found"
    | "exception"
    | "document"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "(base)_about"
    | "(base)_dashboard"
    | "(base)_dashboard_ops"
    | "(base)_dashboard_overview"
    | "(base)_delivery"
    | "(base)_delivery_master_carriers"
    | "(base)_delivery_master_drivers"
    | "(base)_delivery_master"
    | "(base)_delivery_master_routes"
    | "(base)_delivery_ops_exceptions"
    | "(base)_delivery_ops"
    | "(base)_delivery_ops_tasks"
    | "(base)_finance_customer_bills"
    | "(base)_finance_customer"
    | "(base)_finance_customer_settlements"
    | "(base)_finance"
    | "(base)_finance_supplier_bills"
    | "(base)_finance_supplier"
    | "(base)_finance_supplier_settlements"
    | "(base)"
    | "(base)_master_customer_companies"
    | "(base)_master_customer"
    | "(base)_master_customer_list"
    | "(base)_master_customer_operate_[id]"
    | "(base)_master_customer_operate"
    | "(base)_master_customer_sub-accounts"
    | "(base)_master_customer_tags"
    | "(base)_master_goods"
    | "(base)_master_goods_list"
    | "(base)_master_goods_operate_[id]"
    | "(base)_master_goods_operate"
    | "(base)_master_goods_types"
    | "(base)_master_goods_units"
    | "(base)_master"
    | "(base)_master_pricing"
    | "(base)_master_pricing_protocol-goods"
    | "(base)_master_pricing_protocols"
    | "(base)_master_pricing_quotation-goods"
    | "(base)_master_pricing_quotations"
    | "(base)_master_supply"
    | "(base)_master_supply_purchase-rules"
    | "(base)_master_supply_purchasers"
    | "(base)_master_supply_suppliers"
    | "(base)_master_supply_wares"
    | "(base)_orders_after-sales"
    | "(base)_orders_detail_[id]"
    | "(base)_orders_detail"
    | "(base)_orders_edit_[id]"
    | "(base)_orders_edit"
    | "(base)_orders"
    | "(base)_orders_list"
    | "(base)_orders_pickup-tasks"
    | "(base)_purchase"
    | "(base)_purchase_orders"
    | "(base)_purchase_plans"
    | "(base)_reports_after-sales"
    | "(base)_reports"
    | "(base)_reports_purchase_goods"
    | "(base)_reports_purchase"
    | "(base)_reports_purchase_purchasers"
    | "(base)_reports_purchase_suppliers"
    | "(base)_reports_sales_areas"
    | "(base)_reports_sales_categories"
    | "(base)_reports_sales_customers"
    | "(base)_reports_sales_goods"
    | "(base)_reports_sales"
    | "(base)_reports_stock_daily-goods"
    | "(base)_reports_stock_daily"
    | "(base)_reports_stock"
    | "(base)_storage_in"
    | "(base)_storage_in_other"
    | "(base)_storage_in_purchase"
    | "(base)_storage_in_sales-return"
    | "(base)_storage"
    | "(base)_storage_out"
    | "(base)_storage_out_other"
    | "(base)_storage_out_purchase-return"
    | "(base)_storage_out_sale"
    | "(base)_storage_query_batches"
    | "(base)_storage_query"
    | "(base)_storage_query_ledgers"
    | "(base)_storage_query_overview"
    | "(base)_storage_query_stocktaking"
    | "(base)_system_auth_departments"
    | "(base)_system_auth"
    | "(base)_system_auth_menus"
    | "(base)_system_auth_roles_[...slug]"
    | "(base)_system_auth_roles"
    | "(base)_system_auth_users_[id]"
    | "(base)_system_auth_users"
    | "(base)_system"
    | "(base)_system_ops"
    | "(base)_system_ops_notices"
    | "(base)_system_ops_settings"
    | "(base)_system_tools_files"
    | "(base)_system_tools_import-export"
    | "(base)_system_tools"
    | "(base)_system_tools_print-templates"
    | "(base)_traceability"
    | "(base)_traceability_inspection-reports"
    | "(base)_traceability_push-logs"
    | "(base)_traceability_records"
    | "(base)_user-center"
    | "(blank)"
    | "(blank)_login-out"
    | "(blank)_login_code-login"
    | "(blank)_login"
    | "(blank)_login"
    | "(blank)_login_register"
    | "(blank)_login_reset-pwd"
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "root"
    | "root"
    | "root"
    | "root"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document_project"
    | "document_project-link"
    | "document_react"
    | "document_vite"
    | "document_unocss"
    | "document_procomponents"
    | "document_antd"
    | "document_ui"
  >;
}
