/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

//这里只能修改 handle 并且路由组作为布局路由组件 是不能有handle的

import type { ElegantConstRoute } from '@soybean-react/vite-plugin-react-router';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    matchedFiles: ['root', '/src/pages/index.tsx', '/src/pages/loading.tsx', 'root'],
    name: 'root',
    path: '/',
    handle: { i18nKey: 'route.root', title: 'root', constant: true },
    children: [
      {
        matchedFiles: ['(base)', null, null, null],
        name: '(base)',
        children: [
          {
            matchedFiles: [null, '/src/pages/(base)/about/index.tsx', null, null],
            name: '(base)_about',
            path: '/about',
            handle: { i18nKey: 'route.(base)_about', title: '(base)_about', hideInMenu: true }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/dashboard/index.tsx', null, null],
            name: '(base)_dashboard',
            path: '/dashboard',
            handle: {
              i18nKey: 'route.(base)_dashboard',
              title: '(base)_dashboard',
              icon: 'mdi:view-dashboard-outline',
              order: 1
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/dashboard/ops/index.tsx', null, null],
                name: '(base)_dashboard_ops',
                path: '/dashboard/ops',
                handle: {
                  i18nKey: 'route.(base)_dashboard_ops',
                  title: '(base)_dashboard_ops',
                  icon: 'mdi:clipboard-check-outline',
                  order: 2
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/dashboard/overview/index.tsx', null, null],
                name: '(base)_dashboard_overview',
                path: '/dashboard/overview',
                handle: {
                  i18nKey: 'route.(base)_dashboard_overview',
                  title: '(base)_dashboard_overview',
                  icon: 'mdi:chart-line',
                  order: 1
                }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/delivery/index.tsx', null, null],
            name: '(base)_delivery',
            path: '/delivery',
            handle: {
              i18nKey: 'route.(base)_delivery',
              title: '(base)_delivery',
              icon: 'mdi:truck-fast-outline',
              order: 5
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/delivery/master/index.tsx', null, null],
                name: '(base)_delivery_master',
                path: '/delivery/master',
                handle: {
                  i18nKey: 'route.(base)_delivery_master',
                  title: '(base)_delivery_master',
                  icon: 'mdi:card-account-details-outline',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/delivery/master/carriers/index.tsx', null, null],
                    name: '(base)_delivery_master_carriers',
                    path: '/delivery/master/carriers',
                    handle: {
                      i18nKey: 'route.(base)_delivery_master_carriers',
                      title: '(base)_delivery_master_carriers',
                      icon: 'mdi:domain',
                      order: 1
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/delivery/master/drivers/index.tsx', null, null],
                    name: '(base)_delivery_master_drivers',
                    path: '/delivery/master/drivers',
                    handle: {
                      i18nKey: 'route.(base)_delivery_master_drivers',
                      title: '(base)_delivery_master_drivers',
                      icon: 'mdi:account-tie-hat',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/delivery/master/routes/index.tsx', null, null],
                    name: '(base)_delivery_master_routes',
                    path: '/delivery/master/routes',
                    handle: {
                      i18nKey: 'route.(base)_delivery_master_routes',
                      title: '(base)_delivery_master_routes',
                      icon: 'mdi:map-marker-path',
                      order: 3
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/delivery/ops/index.tsx', null, null],
                name: '(base)_delivery_ops',
                path: '/delivery/ops',
                handle: {
                  i18nKey: 'route.(base)_delivery_ops',
                  title: '(base)_delivery_ops',
                  icon: 'mdi:clipboard-text-outline',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/delivery/ops/exceptions/index.tsx', null, null],
                    name: '(base)_delivery_ops_exceptions',
                    path: '/delivery/ops/exceptions',
                    handle: {
                      i18nKey: 'route.(base)_delivery_ops_exceptions',
                      title: '(base)_delivery_ops_exceptions',
                      icon: 'mdi:alert-octagon-outline',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/delivery/ops/tasks/index.tsx', null, null],
                    name: '(base)_delivery_ops_tasks',
                    path: '/delivery/ops/tasks',
                    handle: {
                      i18nKey: 'route.(base)_delivery_ops_tasks',
                      title: '(base)_delivery_ops_tasks',
                      icon: 'mdi:truck-check-outline',
                      order: 1
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/finance/index.tsx', null, null],
            name: '(base)_finance',
            path: '/finance',
            handle: { i18nKey: 'route.(base)_finance', title: '(base)_finance', icon: 'mdi:cash-multiple', order: 6 },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/finance/customer/index.tsx', null, null],
                name: '(base)_finance_customer',
                path: '/finance/customer',
                handle: {
                  i18nKey: 'route.(base)_finance_customer',
                  title: '(base)_finance_customer',
                  icon: 'mdi:account-cash-outline',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/finance/customer/bills/index.tsx', null, null],
                    name: '(base)_finance_customer_bills',
                    path: '/finance/customer/bills',
                    handle: {
                      i18nKey: 'route.(base)_finance_customer_bills',
                      title: '(base)_finance_customer_bills',
                      icon: 'mdi:file-table-outline',
                      order: 1
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/finance/customer/settlements/index.tsx', null, null],
                    name: '(base)_finance_customer_settlements',
                    path: '/finance/customer/settlements',
                    handle: {
                      i18nKey: 'route.(base)_finance_customer_settlements',
                      title: '(base)_finance_customer_settlements',
                      icon: 'mdi:cash-check',
                      order: 2
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/finance/supplier/index.tsx', null, null],
                name: '(base)_finance_supplier',
                path: '/finance/supplier',
                handle: {
                  i18nKey: 'route.(base)_finance_supplier',
                  title: '(base)_finance_supplier',
                  icon: 'mdi:storefront-outline',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/finance/supplier/bills/index.tsx', null, null],
                    name: '(base)_finance_supplier_bills',
                    path: '/finance/supplier/bills',
                    handle: {
                      i18nKey: 'route.(base)_finance_supplier_bills',
                      title: '(base)_finance_supplier_bills',
                      icon: 'mdi:file-table-outline',
                      order: 1
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/finance/supplier/settlements/index.tsx', null, null],
                    name: '(base)_finance_supplier_settlements',
                    path: '/finance/supplier/settlements',
                    handle: {
                      i18nKey: 'route.(base)_finance_supplier_settlements',
                      title: '(base)_finance_supplier_settlements',
                      icon: 'mdi:cash-check',
                      order: 2
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/master/index.tsx', null, null],
            name: '(base)_master',
            path: '/master',
            handle: { i18nKey: 'route.(base)_master', title: '(base)_master', icon: 'mdi:database-outline', order: 9 },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/master/customer/index.tsx', null, null],
                name: '(base)_master_customer',
                path: '/master/customer',
                handle: {
                  i18nKey: 'route.(base)_master_customer',
                  title: '(base)_master_customer',
                  icon: 'mdi:account-group-outline',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/customer/companies/index.tsx', null, null],
                    name: '(base)_master_customer_companies',
                    path: '/master/customer/companies',
                    handle: {
                      i18nKey: 'route.(base)_master_customer_companies',
                      title: '(base)_master_customer_companies',
                      icon: 'mdi:office-building-outline',
                      order: 1
                    },
                    children: [
                      {
                        matchedFiles: [
                          null,
                          '/src/pages/(base)/master/customer/companies/detail/index.tsx',
                          null,
                          null
                        ],
                        name: '(base)_master_customer_companies_detail',
                        path: '/master/customer/companies/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_customer_companies_detail',
                          title: '(base)_master_customer_companies_detail',
                          activeMenu: '/master/customer/companies',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/customer/companies/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_customer_companies_detail_[id]',
                            path: '/master/customer/companies/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_customer_companies_detail_[id]',
                              title: '(base)_master_customer_companies_detail_[id]',
                              activeMenu: '/master/customer/companies',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/customer/detail/index.tsx', null, null],
                    name: '(base)_master_customer_detail',
                    path: '/master/customer/detail',
                    handle: {
                      i18nKey: 'route.(base)_master_customer_detail',
                      title: '(base)_master_customer_detail',
                      activeMenu: '/master/customer/list',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/customer/detail/[id].tsx', null, null],
                        name: '(base)_master_customer_detail_[id]',
                        path: '/master/customer/detail/:id',
                        handle: {
                          i18nKey: 'route.(base)_master_customer_detail_[id]',
                          title: '(base)_master_customer_detail_[id]',
                          activeMenu: '/master/customer/list',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/customer/list/index.tsx', null, null],
                    name: '(base)_master_customer_list',
                    path: '/master/customer/list',
                    handle: {
                      i18nKey: 'route.(base)_master_customer_list',
                      title: '(base)_master_customer_list',
                      icon: 'mdi:format-list-bulleted',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/customer/operate/index.tsx', null, null],
                    name: '(base)_master_customer_operate',
                    path: '/master/customer/operate',
                    handle: {
                      i18nKey: 'route.(base)_master_customer_operate',
                      title: '(base)_master_customer_operate',
                      activeMenu: '/master/customer/list',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/customer/operate/[id].tsx', null, null],
                        name: '(base)_master_customer_operate_[id]',
                        path: '/master/customer/operate/:id',
                        handle: {
                          i18nKey: 'route.(base)_master_customer_operate_[id]',
                          title: '(base)_master_customer_operate_[id]',
                          activeMenu: '/master/customer/list',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/customer/sub-accounts/index.tsx', null, null],
                    name: '(base)_master_customer_sub-accounts',
                    path: '/master/customer/sub-accounts',
                    handle: {
                      i18nKey: 'route.(base)_master_customer_sub-accounts',
                      title: '(base)_master_customer_sub-accounts',
                      icon: 'mdi:account-multiple-outline',
                      order: 4
                    },
                    children: [
                      {
                        matchedFiles: [
                          null,
                          '/src/pages/(base)/master/customer/sub-accounts/detail/index.tsx',
                          null,
                          null
                        ],
                        name: '(base)_master_customer_sub-accounts_detail',
                        path: '/master/customer/sub-accounts/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_customer_sub-accounts_detail',
                          title: '(base)_master_customer_sub-accounts_detail',
                          activeMenu: '/master/customer/sub-accounts',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/customer/sub-accounts/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_customer_sub-accounts_detail_[id]',
                            path: '/master/customer/sub-accounts/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_customer_sub-accounts_detail_[id]',
                              title: '(base)_master_customer_sub-accounts_detail_[id]',
                              activeMenu: '/master/customer/sub-accounts',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/customer/tags/index.tsx', null, null],
                    name: '(base)_master_customer_tags',
                    path: '/master/customer/tags',
                    handle: {
                      i18nKey: 'route.(base)_master_customer_tags',
                      title: '(base)_master_customer_tags',
                      icon: 'mdi:tag-multiple-outline',
                      order: 3
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/customer/tags/detail/index.tsx', null, null],
                        name: '(base)_master_customer_tags_detail',
                        path: '/master/customer/tags/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_customer_tags_detail',
                          title: '(base)_master_customer_tags_detail',
                          activeMenu: '/master/customer/tags',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [null, '/src/pages/(base)/master/customer/tags/detail/[id].tsx', null, null],
                            name: '(base)_master_customer_tags_detail_[id]',
                            path: '/master/customer/tags/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_customer_tags_detail_[id]',
                              title: '(base)_master_customer_tags_detail_[id]',
                              activeMenu: '/master/customer/tags',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/master/goods/index.tsx', null, null],
                name: '(base)_master_goods',
                path: '/master/goods',
                handle: {
                  i18nKey: 'route.(base)_master_goods',
                  title: '(base)_master_goods',
                  icon: 'mdi:shopping-outline',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/goods/detail/index.tsx', null, null],
                    name: '(base)_master_goods_detail',
                    path: '/master/goods/detail',
                    handle: {
                      i18nKey: 'route.(base)_master_goods_detail',
                      title: '(base)_master_goods_detail',
                      activeMenu: '/master/goods/list',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/goods/detail/[id].tsx', null, null],
                        name: '(base)_master_goods_detail_[id]',
                        path: '/master/goods/detail/:id',
                        handle: {
                          i18nKey: 'route.(base)_master_goods_detail_[id]',
                          title: '(base)_master_goods_detail_[id]',
                          activeMenu: '/master/goods/list',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/goods/list/index.tsx', null, null],
                    name: '(base)_master_goods_list',
                    path: '/master/goods/list',
                    handle: {
                      i18nKey: 'route.(base)_master_goods_list',
                      title: '(base)_master_goods_list',
                      icon: 'mdi:format-list-bulleted',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/goods/operate/index.tsx', null, null],
                    name: '(base)_master_goods_operate',
                    path: '/master/goods/operate',
                    handle: {
                      i18nKey: 'route.(base)_master_goods_operate',
                      title: '(base)_master_goods_operate',
                      activeMenu: '/master/goods/list',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/goods/operate/[id].tsx', null, null],
                        name: '(base)_master_goods_operate_[id]',
                        path: '/master/goods/operate/:id',
                        handle: {
                          i18nKey: 'route.(base)_master_goods_operate_[id]',
                          title: '(base)_master_goods_operate_[id]',
                          activeMenu: '/master/goods/list',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/goods/types/index.tsx', null, null],
                    name: '(base)_master_goods_types',
                    path: '/master/goods/types',
                    handle: {
                      i18nKey: 'route.(base)_master_goods_types',
                      title: '(base)_master_goods_types',
                      icon: 'mdi:shape-outline',
                      order: 1
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/goods/types/detail/index.tsx', null, null],
                        name: '(base)_master_goods_types_detail',
                        path: '/master/goods/types/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_goods_types_detail',
                          title: '(base)_master_goods_types_detail',
                          activeMenu: '/master/goods/types',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [null, '/src/pages/(base)/master/goods/types/detail/[id].tsx', null, null],
                            name: '(base)_master_goods_types_detail_[id]',
                            path: '/master/goods/types/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_goods_types_detail_[id]',
                              title: '(base)_master_goods_types_detail_[id]',
                              activeMenu: '/master/goods/types',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/goods/units/index.tsx', null, null],
                    name: '(base)_master_goods_units',
                    path: '/master/goods/units',
                    handle: {
                      i18nKey: 'route.(base)_master_goods_units',
                      title: '(base)_master_goods_units',
                      icon: 'mdi:ruler',
                      order: 3
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/goods/units/detail/index.tsx', null, null],
                        name: '(base)_master_goods_units_detail',
                        path: '/master/goods/units/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_goods_units_detail',
                          title: '(base)_master_goods_units_detail',
                          activeMenu: '/master/goods/units',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [null, '/src/pages/(base)/master/goods/units/detail/[id].tsx', null, null],
                            name: '(base)_master_goods_units_detail_[id]',
                            path: '/master/goods/units/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_goods_units_detail_[id]',
                              title: '(base)_master_goods_units_detail_[id]',
                              activeMenu: '/master/goods/units',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/master/pricing/index.tsx', null, null],
                name: '(base)_master_pricing',
                path: '/master/pricing',
                handle: {
                  i18nKey: 'route.(base)_master_pricing',
                  title: '(base)_master_pricing',
                  icon: 'mdi:tag-outline',
                  order: 3
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/pricing/protocols/index.tsx', null, null],
                    name: '(base)_master_pricing_protocols',
                    path: '/master/pricing/protocols',
                    handle: {
                      i18nKey: 'route.(base)_master_pricing_protocols',
                      title: '(base)_master_pricing_protocols',
                      icon: 'mdi:file-sign',
                      order: 2
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/pricing/protocols/detail/index.tsx', null, null],
                        name: '(base)_master_pricing_protocols_detail',
                        path: '/master/pricing/protocols/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_pricing_protocols_detail',
                          title: '(base)_master_pricing_protocols_detail',
                          activeMenu: '/master/pricing/protocols',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/pricing/protocols/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_pricing_protocols_detail_[id]',
                            path: '/master/pricing/protocols/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_pricing_protocols_detail_[id]',
                              title: '(base)_master_pricing_protocols_detail_[id]',
                              activeMenu: '/master/pricing/protocols',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/pricing/quotations/index.tsx', null, null],
                    name: '(base)_master_pricing_quotations',
                    path: '/master/pricing/quotations',
                    handle: {
                      i18nKey: 'route.(base)_master_pricing_quotations',
                      title: '(base)_master_pricing_quotations',
                      icon: 'mdi:file-document-outline',
                      order: 1
                    },
                    children: [
                      {
                        matchedFiles: [
                          null,
                          '/src/pages/(base)/master/pricing/quotations/detail/index.tsx',
                          null,
                          null
                        ],
                        name: '(base)_master_pricing_quotations_detail',
                        path: '/master/pricing/quotations/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_pricing_quotations_detail',
                          title: '(base)_master_pricing_quotations_detail',
                          activeMenu: '/master/pricing/quotations',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/pricing/quotations/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_pricing_quotations_detail_[id]',
                            path: '/master/pricing/quotations/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_pricing_quotations_detail_[id]',
                              title: '(base)_master_pricing_quotations_detail_[id]',
                              activeMenu: '/master/pricing/quotations',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/master/supply/index.tsx', null, null],
                name: '(base)_master_supply',
                path: '/master/supply',
                handle: {
                  i18nKey: 'route.(base)_master_supply',
                  title: '(base)_master_supply',
                  icon: 'mdi:truck-outline',
                  order: 4
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/supply/purchase-rules/index.tsx', null, null],
                    name: '(base)_master_supply_purchase-rules',
                    path: '/master/supply/purchase-rules',
                    handle: {
                      i18nKey: 'route.(base)_master_supply_purchase-rules',
                      title: '(base)_master_supply_purchase-rules',
                      icon: 'mdi:clipboard-list-outline',
                      order: 3
                    },
                    children: [
                      {
                        matchedFiles: [
                          null,
                          '/src/pages/(base)/master/supply/purchase-rules/detail/index.tsx',
                          null,
                          null
                        ],
                        name: '(base)_master_supply_purchase-rules_detail',
                        path: '/master/supply/purchase-rules/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_supply_purchase-rules_detail',
                          title: '(base)_master_supply_purchase-rules_detail',
                          activeMenu: '/master/supply/purchase-rules',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/supply/purchase-rules/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_supply_purchase-rules_detail_[id]',
                            path: '/master/supply/purchase-rules/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_supply_purchase-rules_detail_[id]',
                              title: '(base)_master_supply_purchase-rules_detail_[id]',
                              activeMenu: '/master/supply/purchase-rules',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/supply/purchasers/index.tsx', null, null],
                    name: '(base)_master_supply_purchasers',
                    path: '/master/supply/purchasers',
                    handle: {
                      i18nKey: 'route.(base)_master_supply_purchasers',
                      title: '(base)_master_supply_purchasers',
                      icon: 'mdi:account-tie-outline',
                      order: 2
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/supply/purchasers/detail/index.tsx', null, null],
                        name: '(base)_master_supply_purchasers_detail',
                        path: '/master/supply/purchasers/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_supply_purchasers_detail',
                          title: '(base)_master_supply_purchasers_detail',
                          activeMenu: '/master/supply/purchasers',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/supply/purchasers/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_supply_purchasers_detail_[id]',
                            path: '/master/supply/purchasers/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_supply_purchasers_detail_[id]',
                              title: '(base)_master_supply_purchasers_detail_[id]',
                              activeMenu: '/master/supply/purchasers',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/supply/suppliers/index.tsx', null, null],
                    name: '(base)_master_supply_suppliers',
                    path: '/master/supply/suppliers',
                    handle: {
                      i18nKey: 'route.(base)_master_supply_suppliers',
                      title: '(base)_master_supply_suppliers',
                      icon: 'mdi:truck-delivery-outline',
                      order: 1
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/supply/suppliers/detail/index.tsx', null, null],
                        name: '(base)_master_supply_suppliers_detail',
                        path: '/master/supply/suppliers/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_supply_suppliers_detail',
                          title: '(base)_master_supply_suppliers_detail',
                          activeMenu: '/master/supply/suppliers',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [
                              null,
                              '/src/pages/(base)/master/supply/suppliers/detail/[id].tsx',
                              null,
                              null
                            ],
                            name: '(base)_master_supply_suppliers_detail_[id]',
                            path: '/master/supply/suppliers/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_supply_suppliers_detail_[id]',
                              title: '(base)_master_supply_suppliers_detail_[id]',
                              activeMenu: '/master/supply/suppliers',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/master/supply/wares/index.tsx', null, null],
                    name: '(base)_master_supply_wares',
                    path: '/master/supply/wares',
                    handle: {
                      i18nKey: 'route.(base)_master_supply_wares',
                      title: '(base)_master_supply_wares',
                      icon: 'mdi:archive-outline',
                      order: 4
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/master/supply/wares/detail/index.tsx', null, null],
                        name: '(base)_master_supply_wares_detail',
                        path: '/master/supply/wares/detail',
                        handle: {
                          i18nKey: 'route.(base)_master_supply_wares_detail',
                          title: '(base)_master_supply_wares_detail',
                          activeMenu: '/master/supply/wares',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [null, '/src/pages/(base)/master/supply/wares/detail/[id].tsx', null, null],
                            name: '(base)_master_supply_wares_detail_[id]',
                            path: '/master/supply/wares/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_master_supply_wares_detail_[id]',
                              title: '(base)_master_supply_wares_detail_[id]',
                              activeMenu: '/master/supply/wares',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/orders/index.tsx', null, null],
            name: '(base)_orders',
            path: '/orders',
            handle: {
              i18nKey: 'route.(base)_orders',
              title: '(base)_orders',
              icon: 'mdi:clipboard-list-outline',
              order: 2
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/orders/after-sales/index.tsx', null, null],
                name: '(base)_orders_after-sales',
                path: '/orders/after-sales',
                handle: {
                  i18nKey: 'route.(base)_orders_after-sales',
                  title: '(base)_orders_after-sales',
                  icon: 'mdi:backup-restore',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/orders/after-sales/detail/index.tsx', null, null],
                    name: '(base)_orders_after-sales_detail',
                    path: '/orders/after-sales/detail',
                    handle: {
                      i18nKey: 'route.(base)_orders_after-sales_detail',
                      title: '(base)_orders_after-sales_detail',
                      activeMenu: '/orders/after-sales',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/orders/after-sales/detail/[id].tsx', null, null],
                        name: '(base)_orders_after-sales_detail_[id]',
                        path: '/orders/after-sales/detail/:id',
                        handle: {
                          i18nKey: 'route.(base)_orders_after-sales_detail_[id]',
                          title: '(base)_orders_after-sales_detail_[id]',
                          activeMenu: '/orders/after-sales',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/orders/after-sales/operate/index.tsx', null, null],
                    name: '(base)_orders_after-sales_operate',
                    path: '/orders/after-sales/operate',
                    handle: {
                      i18nKey: 'route.(base)_orders_after-sales_operate',
                      title: '(base)_orders_after-sales_operate',
                      activeMenu: '/orders/after-sales',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/orders/after-sales/operate/[id].tsx', null, null],
                        name: '(base)_orders_after-sales_operate_[id]',
                        path: '/orders/after-sales/operate/:id',
                        handle: {
                          i18nKey: 'route.(base)_orders_after-sales_operate_[id]',
                          title: '(base)_orders_after-sales_operate_[id]',
                          activeMenu: '/orders/after-sales',
                          hideInMenu: true
                        }
                      }
                    ]
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/orders/detail/index.tsx', null, null],
                name: '(base)_orders_detail',
                path: '/orders/detail',
                handle: {
                  i18nKey: 'route.(base)_orders_detail',
                  title: '(base)_orders_detail',
                  activeMenu: '/orders/list',
                  hideInMenu: true
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/orders/detail/[id].tsx', null, null],
                    name: '(base)_orders_detail_[id]',
                    path: '/orders/detail/:id',
                    handle: {
                      i18nKey: 'route.(base)_orders_detail_[id]',
                      title: '(base)_orders_detail_[id]',
                      activeMenu: '/orders/list',
                      hideInMenu: true
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/orders/operate/index.tsx', null, null],
                name: '(base)_orders_operate',
                path: '/orders/operate',
                handle: {
                  i18nKey: 'route.(base)_orders_operate',
                  title: '(base)_orders_operate',
                  activeMenu: '/orders/list',
                  hideInMenu: true
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/orders/operate/[id].tsx', null, null],
                    name: '(base)_orders_operate_[id]',
                    path: '/orders/operate/:id',
                    handle: {
                      i18nKey: 'route.(base)_orders_operate_[id]',
                      title: '(base)_orders_operate_[id]',
                      activeMenu: '/orders/list',
                      hideInMenu: true
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/orders/list/index.tsx', null, null],
                name: '(base)_orders_list',
                path: '/orders/list',
                handle: {
                  i18nKey: 'route.(base)_orders_list',
                  title: '(base)_orders_list',
                  icon: 'mdi:format-list-bulleted',
                  order: 1
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/orders/pickup-tasks/index.tsx', null, null],
                name: '(base)_orders_pickup-tasks',
                path: '/orders/pickup-tasks',
                handle: {
                  i18nKey: 'route.(base)_orders_pickup-tasks',
                  title: '(base)_orders_pickup-tasks',
                  icon: 'mdi:package-variant-closed',
                  order: 3
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/orders/pickup-tasks/detail/index.tsx', null, null],
                    name: '(base)_orders_pickup-tasks_detail',
                    path: '/orders/pickup-tasks/detail',
                    handle: {
                      i18nKey: 'route.(base)_orders_pickup-tasks_detail',
                      title: '(base)_orders_pickup-tasks_detail',
                      activeMenu: '/orders/pickup-tasks',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/orders/pickup-tasks/detail/[id].tsx', null, null],
                        name: '(base)_orders_pickup-tasks_detail_[id]',
                        path: '/orders/pickup-tasks/detail/:id',
                        handle: {
                          i18nKey: 'route.(base)_orders_pickup-tasks_detail_[id]',
                          title: '(base)_orders_pickup-tasks_detail_[id]',
                          activeMenu: '/orders/pickup-tasks',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/orders/pickup-tasks/operate/index.tsx', null, null],
                    name: '(base)_orders_pickup-tasks_operate',
                    path: '/orders/pickup-tasks/operate',
                    handle: {
                      i18nKey: 'route.(base)_orders_pickup-tasks_operate',
                      title: '(base)_orders_pickup-tasks_operate',
                      activeMenu: '/orders/pickup-tasks',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/orders/pickup-tasks/operate/[id].tsx', null, null],
                        name: '(base)_orders_pickup-tasks_operate_[id]',
                        path: '/orders/pickup-tasks/operate/:id',
                        handle: {
                          i18nKey: 'route.(base)_orders_pickup-tasks_operate_[id]',
                          title: '(base)_orders_pickup-tasks_operate_[id]',
                          activeMenu: '/orders/pickup-tasks',
                          hideInMenu: true
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/purchase/index.tsx', null, null],
            name: '(base)_purchase',
            path: '/purchase',
            handle: {
              i18nKey: 'route.(base)_purchase',
              title: '(base)_purchase',
              icon: 'mdi:cart-arrow-down',
              order: 3
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/purchase/orders/index.tsx', null, null],
                name: '(base)_purchase_orders',
                path: '/purchase/orders',
                handle: {
                  i18nKey: 'route.(base)_purchase_orders',
                  title: '(base)_purchase_orders',
                  icon: 'mdi:file-document-outline',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, null, null, null],
                    name: '(base)_purchase_orders_detail',
                    path: '/purchase/orders/detail',
                    handle: {
                      i18nKey: 'route.(base)_purchase_orders_detail',
                      title: '(base)_purchase_orders_detail',
                      activeMenu: '/purchase/orders',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/purchase/orders/detail/[id].tsx', null, null],
                        name: '(base)_purchase_orders_detail_[id]',
                        path: '/purchase/orders/detail/:id',
                        handle: {
                          i18nKey: 'route.(base)_purchase_orders_detail_[id]',
                          title: '(base)_purchase_orders_detail_[id]',
                          activeMenu: '/purchase/orders',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/purchase/orders/operate/index.tsx', null, null],
                    name: '(base)_purchase_orders_operate',
                    path: '/purchase/orders/operate',
                    handle: {
                      i18nKey: 'route.(base)_purchase_orders_operate',
                      title: '(base)_purchase_orders_operate',
                      activeMenu: '/purchase/orders',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/purchase/orders/operate/[id].tsx', null, null],
                        name: '(base)_purchase_orders_operate_[id]',
                        path: '/purchase/orders/operate/:id',
                        handle: {
                          i18nKey: 'route.(base)_purchase_orders_operate_[id]',
                          title: '(base)_purchase_orders_operate_[id]',
                          activeMenu: '/purchase/orders',
                          hideInMenu: true
                        }
                      }
                    ]
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/purchase/plans/index.tsx', null, null],
                name: '(base)_purchase_plans',
                path: '/purchase/plans',
                handle: {
                  i18nKey: 'route.(base)_purchase_plans',
                  title: '(base)_purchase_plans',
                  icon: 'mdi:calendar-check-outline',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, null, null, null],
                    name: '(base)_purchase_plans_detail',
                    path: '/purchase/plans/detail',
                    handle: {
                      i18nKey: 'route.(base)_purchase_plans_detail',
                      title: '(base)_purchase_plans_detail',
                      activeMenu: '/purchase/plans',
                      hideInMenu: true
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/purchase/plans/detail/[id].tsx', null, null],
                        name: '(base)_purchase_plans_detail_[id]',
                        path: '/purchase/plans/detail/:id',
                        handle: {
                          i18nKey: 'route.(base)_purchase_plans_detail_[id]',
                          title: '(base)_purchase_plans_detail_[id]',
                          activeMenu: '/purchase/plans',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/purchase/plans/operate/index.tsx', null, null],
                    name: '(base)_purchase_plans_operate',
                    path: '/purchase/plans/operate',
                    handle: {
                      i18nKey: 'route.(base)_purchase_plans_operate',
                      title: '(base)_purchase_plans_operate',
                      activeMenu: '/purchase/plans',
                      hideInMenu: true
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/reports/index.tsx', null, null],
            name: '(base)_reports',
            path: '/reports',
            handle: {
              i18nKey: 'route.(base)_reports',
              title: '(base)_reports',
              icon: 'mdi:chart-box-outline',
              order: 8
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/reports/after-sales/index.tsx', null, null],
                name: '(base)_reports_after-sales',
                path: '/reports/after-sales',
                handle: {
                  i18nKey: 'route.(base)_reports_after-sales',
                  title: '(base)_reports_after-sales',
                  icon: 'mdi:backup-restore',
                  order: 2
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/reports/purchase/index.tsx', null, null],
                name: '(base)_reports_purchase',
                path: '/reports/purchase',
                handle: {
                  i18nKey: 'route.(base)_reports_purchase',
                  title: '(base)_reports_purchase',
                  icon: 'mdi:cart-arrow-down',
                  order: 4
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/purchase/goods/index.tsx', null, null],
                    name: '(base)_reports_purchase_goods',
                    path: '/reports/purchase/goods',
                    handle: {
                      i18nKey: 'route.(base)_reports_purchase_goods',
                      title: '(base)_reports_purchase_goods',
                      icon: 'mdi:package-variant',
                      order: 1
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/purchase/purchasers/index.tsx', null, null],
                    name: '(base)_reports_purchase_purchasers',
                    path: '/reports/purchase/purchasers',
                    handle: {
                      i18nKey: 'route.(base)_reports_purchase_purchasers',
                      title: '(base)_reports_purchase_purchasers',
                      icon: 'mdi:account-tie-outline',
                      order: 3
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/purchase/suppliers/index.tsx', null, null],
                    name: '(base)_reports_purchase_suppliers',
                    path: '/reports/purchase/suppliers',
                    handle: {
                      i18nKey: 'route.(base)_reports_purchase_suppliers',
                      title: '(base)_reports_purchase_suppliers',
                      icon: 'mdi:truck-outline',
                      order: 2
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/reports/sales/index.tsx', null, null],
                name: '(base)_reports_sales',
                path: '/reports/sales',
                handle: {
                  i18nKey: 'route.(base)_reports_sales',
                  title: '(base)_reports_sales',
                  icon: 'mdi:chart-line',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/sales/areas/index.tsx', null, null],
                    name: '(base)_reports_sales_areas',
                    path: '/reports/sales/areas',
                    handle: {
                      i18nKey: 'route.(base)_reports_sales_areas',
                      title: '(base)_reports_sales_areas',
                      icon: 'mdi:map-outline',
                      order: 4
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/sales/categories/index.tsx', null, null],
                    name: '(base)_reports_sales_categories',
                    path: '/reports/sales/categories',
                    handle: {
                      i18nKey: 'route.(base)_reports_sales_categories',
                      title: '(base)_reports_sales_categories',
                      icon: 'mdi:shape-outline',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/sales/customers/index.tsx', null, null],
                    name: '(base)_reports_sales_customers',
                    path: '/reports/sales/customers',
                    handle: {
                      i18nKey: 'route.(base)_reports_sales_customers',
                      title: '(base)_reports_sales_customers',
                      icon: 'mdi:account-group-outline',
                      order: 3
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/sales/goods/index.tsx', null, null],
                    name: '(base)_reports_sales_goods',
                    path: '/reports/sales/goods',
                    handle: {
                      i18nKey: 'route.(base)_reports_sales_goods',
                      title: '(base)_reports_sales_goods',
                      icon: 'mdi:package-variant',
                      order: 1
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/reports/stock/index.tsx', null, null],
                name: '(base)_reports_stock',
                path: '/reports/stock',
                handle: {
                  i18nKey: 'route.(base)_reports_stock',
                  title: '(base)_reports_stock',
                  icon: 'mdi:warehouse',
                  order: 3
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/stock/daily/index.tsx', null, null],
                    name: '(base)_reports_stock_daily',
                    path: '/reports/stock/daily',
                    handle: {
                      i18nKey: 'route.(base)_reports_stock_daily',
                      title: '(base)_reports_stock_daily',
                      icon: 'mdi:calendar-today',
                      order: 1
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/reports/stock/daily-goods/index.tsx', null, null],
                    name: '(base)_reports_stock_daily-goods',
                    path: '/reports/stock/daily-goods',
                    handle: {
                      i18nKey: 'route.(base)_reports_stock_daily-goods',
                      title: '(base)_reports_stock_daily-goods',
                      icon: 'mdi:calendar-month-outline',
                      order: 2
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/storage/index.tsx', null, null],
            name: '(base)_storage',
            path: '/storage',
            handle: { i18nKey: 'route.(base)_storage', title: '(base)_storage', icon: 'mdi:warehouse', order: 4 },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/storage/in/index.tsx', null, null],
                name: '(base)_storage_in',
                path: '/storage/in',
                handle: {
                  i18nKey: 'route.(base)_storage_in',
                  title: '(base)_storage_in',
                  icon: 'mdi:inbox-arrow-down',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/in/other/index.tsx', null, null],
                    name: '(base)_storage_in_other',
                    path: '/storage/in/other',
                    handle: {
                      i18nKey: 'route.(base)_storage_in_other',
                      title: '(base)_storage_in_other',
                      icon: 'mdi:inbox-full-outline',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/in/purchase/index.tsx', null, null],
                    name: '(base)_storage_in_purchase',
                    path: '/storage/in/purchase',
                    handle: {
                      i18nKey: 'route.(base)_storage_in_purchase',
                      title: '(base)_storage_in_purchase',
                      icon: 'mdi:truck-check-outline',
                      order: 1
                    },
                    children: [
                      {
                        matchedFiles: [null, null, null, null],
                        name: '(base)_storage_in_purchase_detail',
                        path: '/storage/in/purchase/detail',
                        handle: {
                          i18nKey: 'route.(base)_storage_in_purchase_detail',
                          title: '(base)_storage_in_purchase_detail',
                          activeMenu: '/storage/in/purchase',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [null, '/src/pages/(base)/storage/in/purchase/detail/[id].tsx', null, null],
                            name: '(base)_storage_in_purchase_detail_[id]',
                            path: '/storage/in/purchase/detail/:id',
                            handle: {
                              i18nKey: 'route.(base)_storage_in_purchase_detail_[id]',
                              title: '(base)_storage_in_purchase_detail_[id]',
                              activeMenu: '/storage/in/purchase',
                              hideInMenu: true
                            }
                          }
                        ]
                      },
                      {
                        matchedFiles: [null, '/src/pages/(base)/storage/in/purchase/operate/index.tsx', null, null],
                        name: '(base)_storage_in_purchase_operate',
                        path: '/storage/in/purchase/operate',
                        handle: {
                          i18nKey: 'route.(base)_storage_in_purchase_operate',
                          title: '(base)_storage_in_purchase_operate',
                          activeMenu: '/storage/in/purchase',
                          hideInMenu: true
                        },
                        children: [
                          {
                            matchedFiles: [null, '/src/pages/(base)/storage/in/purchase/operate/[id].tsx', null, null],
                            name: '(base)_storage_in_purchase_operate_[id]',
                            path: '/storage/in/purchase/operate/:id',
                            handle: {
                              i18nKey: 'route.(base)_storage_in_purchase_operate_[id]',
                              title: '(base)_storage_in_purchase_operate_[id]',
                              activeMenu: '/storage/in/purchase',
                              hideInMenu: true
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/in/sales-return/index.tsx', null, null],
                    name: '(base)_storage_in_sales-return',
                    path: '/storage/in/sales-return',
                    handle: {
                      i18nKey: 'route.(base)_storage_in_sales-return',
                      title: '(base)_storage_in_sales-return',
                      icon: 'mdi:keyboard-return',
                      order: 3
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/storage/out/index.tsx', null, null],
                name: '(base)_storage_out',
                path: '/storage/out',
                handle: {
                  i18nKey: 'route.(base)_storage_out',
                  title: '(base)_storage_out',
                  icon: 'mdi:inbox-arrow-up',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/out/other/index.tsx', null, null],
                    name: '(base)_storage_out_other',
                    path: '/storage/out/other',
                    handle: {
                      i18nKey: 'route.(base)_storage_out_other',
                      title: '(base)_storage_out_other',
                      icon: 'mdi:package-up',
                      order: 3
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/out/purchase-return/index.tsx', null, null],
                    name: '(base)_storage_out_purchase-return',
                    path: '/storage/out/purchase-return',
                    handle: {
                      i18nKey: 'route.(base)_storage_out_purchase-return',
                      title: '(base)_storage_out_purchase-return',
                      icon: 'mdi:truck-remove-outline',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/out/sale/index.tsx', null, null],
                    name: '(base)_storage_out_sale',
                    path: '/storage/out/sale',
                    handle: {
                      i18nKey: 'route.(base)_storage_out_sale',
                      title: '(base)_storage_out_sale',
                      icon: 'mdi:truck-delivery-outline',
                      order: 1
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/storage/query/index.tsx', null, null],
                name: '(base)_storage_query',
                path: '/storage/query',
                handle: {
                  i18nKey: 'route.(base)_storage_query',
                  title: '(base)_storage_query',
                  icon: 'mdi:database-search-outline',
                  order: 3
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/query/batches/index.tsx', null, null],
                    name: '(base)_storage_query_batches',
                    path: '/storage/query/batches',
                    handle: {
                      i18nKey: 'route.(base)_storage_query_batches',
                      title: '(base)_storage_query_batches',
                      icon: 'mdi:layers-outline',
                      order: 3
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/query/ledgers/index.tsx', null, null],
                    name: '(base)_storage_query_ledgers',
                    path: '/storage/query/ledgers',
                    handle: {
                      i18nKey: 'route.(base)_storage_query_ledgers',
                      title: '(base)_storage_query_ledgers',
                      icon: 'mdi:book-open-outline',
                      order: 4
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/query/overview/index.tsx', null, null],
                    name: '(base)_storage_query_overview',
                    path: '/storage/query/overview',
                    handle: {
                      i18nKey: 'route.(base)_storage_query_overview',
                      title: '(base)_storage_query_overview',
                      icon: 'mdi:view-dashboard-variant-outline',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/storage/query/stocktaking/index.tsx', null, null],
                    name: '(base)_storage_query_stocktaking',
                    path: '/storage/query/stocktaking',
                    handle: {
                      i18nKey: 'route.(base)_storage_query_stocktaking',
                      title: '(base)_storage_query_stocktaking',
                      icon: 'mdi:clipboard-check-outline',
                      order: 1
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/system/index.tsx', null, null],
            name: '(base)_system',
            path: '/system',
            handle: { i18nKey: 'route.(base)_system', title: '(base)_system', icon: 'mdi:cog-outline', order: 10 },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/system/auth/index.tsx', null, null],
                name: '(base)_system_auth',
                path: '/system/auth',
                handle: {
                  i18nKey: 'route.(base)_system_auth',
                  title: '(base)_system_auth',
                  icon: 'mdi:shield-account-outline',
                  order: 1
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/auth/departments/index.tsx', null, null],
                    name: '(base)_system_auth_departments',
                    path: '/system/auth/departments',
                    handle: {
                      i18nKey: 'route.(base)_system_auth_departments',
                      title: '(base)_system_auth_departments',
                      icon: 'mdi:sitemap-outline',
                      order: 4
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/auth/menus/index.tsx', null, null],
                    name: '(base)_system_auth_menus',
                    path: '/system/auth/menus',
                    handle: {
                      i18nKey: 'route.(base)_system_auth_menus',
                      title: '(base)_system_auth_menus',
                      icon: 'mdi:menu',
                      order: 3
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/auth/roles/index.tsx', null, null],
                    name: '(base)_system_auth_roles',
                    path: '/system/auth/roles',
                    handle: {
                      i18nKey: 'route.(base)_system_auth_roles',
                      title: '(base)_system_auth_roles',
                      icon: 'mdi:account-key-outline',
                      order: 2
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/system/auth/roles/[...slug].tsx', null, null],
                        name: '(base)_system_auth_roles_[...slug]',
                        path: '/system/auth/roles/*',
                        handle: {
                          i18nKey: 'route.(base)_system_auth_roles_[...slug]',
                          title: '(base)_system_auth_roles_[...slug]',
                          activeMenu: '/system/auth/roles',
                          hideInMenu: true
                        }
                      }
                    ]
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/auth/users/index.tsx', null, null],
                    name: '(base)_system_auth_users',
                    path: '/system/auth/users',
                    handle: {
                      i18nKey: 'route.(base)_system_auth_users',
                      title: '(base)_system_auth_users',
                      icon: 'mdi:account-outline',
                      order: 1
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(base)/system/auth/users/[id].tsx', null, null],
                        name: '(base)_system_auth_users_[id]',
                        path: '/system/auth/users/:id',
                        handle: {
                          i18nKey: 'route.(base)_system_auth_users_[id]',
                          title: '(base)_system_auth_users_[id]',
                          activeMenu: '/system/auth/users',
                          hideInMenu: true
                        }
                      }
                    ]
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/system/ops/index.tsx', null, null],
                name: '(base)_system_ops',
                path: '/system/ops',
                handle: {
                  i18nKey: 'route.(base)_system_ops',
                  title: '(base)_system_ops',
                  icon: 'mdi:toolbox-outline',
                  order: 2
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/ops/notices/index.tsx', null, null],
                    name: '(base)_system_ops_notices',
                    path: '/system/ops/notices',
                    handle: {
                      i18nKey: 'route.(base)_system_ops_notices',
                      title: '(base)_system_ops_notices',
                      icon: 'mdi:bell-outline',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/ops/settings/index.tsx', null, null],
                    name: '(base)_system_ops_settings',
                    path: '/system/ops/settings',
                    handle: {
                      i18nKey: 'route.(base)_system_ops_settings',
                      title: '(base)_system_ops_settings',
                      icon: 'mdi:tune-variant',
                      order: 1
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/system/tools/index.tsx', null, null],
                name: '(base)_system_tools',
                path: '/system/tools',
                handle: {
                  i18nKey: 'route.(base)_system_tools',
                  title: '(base)_system_tools',
                  icon: 'mdi:printer-outline',
                  order: 3
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/tools/files/index.tsx', null, null],
                    name: '(base)_system_tools_files',
                    path: '/system/tools/files',
                    handle: {
                      i18nKey: 'route.(base)_system_tools_files',
                      title: '(base)_system_tools_files',
                      icon: 'mdi:folder-outline',
                      order: 3
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/tools/import-export/index.tsx', null, null],
                    name: '(base)_system_tools_import-export',
                    path: '/system/tools/import-export',
                    handle: {
                      i18nKey: 'route.(base)_system_tools_import-export',
                      title: '(base)_system_tools_import-export',
                      icon: 'mdi:swap-horizontal',
                      order: 2
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(base)/system/tools/print-templates/index.tsx', null, null],
                    name: '(base)_system_tools_print-templates',
                    path: '/system/tools/print-templates',
                    handle: {
                      i18nKey: 'route.(base)_system_tools_print-templates',
                      title: '(base)_system_tools_print-templates',
                      icon: 'mdi:printer',
                      order: 1
                    }
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/traceability/index.tsx', null, null],
            name: '(base)_traceability',
            path: '/traceability',
            handle: {
              i18nKey: 'route.(base)_traceability',
              title: '(base)_traceability',
              icon: 'mdi:qrcode-scan',
              order: 7
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/traceability/inspection-reports/index.tsx', null, null],
                name: '(base)_traceability_inspection-reports',
                path: '/traceability/inspection-reports',
                handle: {
                  i18nKey: 'route.(base)_traceability_inspection-reports',
                  title: '(base)_traceability_inspection-reports',
                  icon: 'mdi:file-certificate-outline',
                  order: 1
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/traceability/push-logs/index.tsx', null, null],
                name: '(base)_traceability_push-logs',
                path: '/traceability/push-logs',
                handle: {
                  i18nKey: 'route.(base)_traceability_push-logs',
                  title: '(base)_traceability_push-logs',
                  icon: 'mdi:cloud-upload-outline',
                  order: 3
                }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/traceability/records/index.tsx', null, null],
                name: '(base)_traceability_records',
                path: '/traceability/records',
                handle: {
                  i18nKey: 'route.(base)_traceability_records',
                  title: '(base)_traceability_records',
                  icon: 'mdi:timeline-text-outline',
                  order: 2
                }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(base)/user-center/index.tsx', null, null],
            name: '(base)_user-center',
            path: '/user-center',
            handle: { i18nKey: 'route.(base)_user-center', title: '(base)_user-center', hideInMenu: true }
          }
        ],
        path: null
      },
      {
        matchedFiles: ['(blank)', null, null, null],
        name: '(blank)',
        children: [
          {
            matchedFiles: ['(blank)_login', '/src/pages/(blank)/login/index.tsx', null, null],
            name: '(blank)_login',
            path: '/login',
            handle: { i18nKey: 'route.(blank)_login', title: '(blank)_login', constant: true },
            children: [
              {
                matchedFiles: [null, '/src/pages/(blank)/login/code-login/index.tsx', null, null],
                name: '(blank)_login_code-login',
                path: '/login/code-login',
                handle: { i18nKey: 'route.(blank)_login_code-login', title: '(blank)_login_code-login', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/register/index.tsx', null, null],
                name: '(blank)_login_register',
                path: '/login/register',
                handle: { i18nKey: 'route.(blank)_login_register', title: '(blank)_login_register', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/reset-pwd/index.tsx', null, null],
                name: '(blank)_login_reset-pwd',
                path: '/login/reset-pwd',
                handle: { i18nKey: 'route.(blank)_login_reset-pwd', title: '(blank)_login_reset-pwd', constant: true }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(blank)/login-out/index.tsx', null, null],
            name: '(blank)_login-out',
            path: '/login-out',
            handle: { i18nKey: 'route.(blank)_login-out', title: '(blank)_login-out', constant: true }
          }
        ],
        path: null
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/403/index.tsx', null, null],
        name: '403',
        path: '/403',
        handle: { i18nKey: 'route.403', title: '403', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: '404',
        path: '/404',
        handle: { i18nKey: 'route.404', title: '404', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/500/index.tsx', null, null],
        name: '500',
        path: '/500',
        handle: { i18nKey: 'route.500', title: '500', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/iframe-page/index.tsx', null, null],
        name: 'iframe-page',
        path: '/iframe-page',
        handle: { i18nKey: 'route.iframe-page', title: 'iframe-page', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: 'notFound',
        path: '*',
        handle: { i18nKey: 'route.notFound', title: 'notFound', constant: true }
      }
    ]
  }
];
